### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by fbremer** [chapmanb/bcbb#119]
I couldn't find any licence info in this repo, I was hoping to use some code from align/adaptor_trim.py for a project rather than roll my own.

**Comment by chapmanb** [comment]
Forest;
Thanks for re-using this code and sorry about the lack of an explicit license. I've added text to the main README, and all code is available under the MIT license and docs/images under CC0 for unrestricted use. Definitely feel free to re-use at will and thanks again.
