### ISSUE TITLE
Need Nucleotide or protein alphabet

### ISSUE THREAD

**Issue by camilo-monge** [chapmanb/bcbb#121]
Hello, I'm trying to run gff_to_genbank.py in python3, however, I'm getting the following error.
`File "/home/camilo/.local/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 631, in _write_the_first_line
    raise ValueError("Need a Nucleotide or Protein alphabet")
ValueError: Need a Nucleotide or Protein alphabet`
Any ideas? Thanks in advance

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. I'm not able to replicate this with Python 3 and a small test GFF and fasta input file, so not entirely sure what is wrong. Would you be able to share some information to help debug:

- What version of bcbio.gff and Biopython are you running?
- Do you have a minimal GFF and fasta file input that can replicate the issue we could use for debugging?

Thanks much for the report and help debugging.

**Comment by camilo-monge** [comment]
I'm sorry, it was my mistake, the gff file had a fasta line at the end.
